name: TubesZB MGM24 HW Zigbee
device: MGM240PA32VNN
base_project: src/ncp-uart-hw
filename: "{manifest_name}_{ezsp_version}"

gbl:
  fw_type: ncp-uart-hw
  dynamic: ["ezsp_version"]
  baudrate: 115200

configuration:
  SL_RAIL_UTIL_PTI_MODE: RAIL_PTI_MODE_DISABLED # enabled in original tubeszb fw
  SL_IOSTREAM_USART_VCOM_BAUDRATE: 115200
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: usartHwFlowControlCtsAndRts

slcp_defines:
  EMBER_ADDRESS_TABLE_SIZE: 16
  EMBER_MULTICAST_TABLE_SIZE: 16

c_defines:
  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_USART_VCOM_TX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_TX_PIN:  6

  SL_IOSTREAM_USART_VCOM_RX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_RX_PIN:  5

  SL_IOSTREAM_USART_VCOM_CTS_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_CTS_PIN:  7

  SL_IOSTREAM_USART_VCOM_RTS_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_RTS_PIN:  8

  # SL_APPLICATION_PRODUCT_ID: '{0x74, 0x75, 0x62, 0x65, 0x73, 0x7A, 0x62, 0x66, 0x69, 0x72, 0x6D, 0x77, 0x61, 0x72, 0x65, 0x73}'

  SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE: 64

  EMBER_APS_UNICAST_MESSAGE_COUNT: 20
  EMBER_BROADCAST_TABLE_SIZE: 30
  EMBER_NEIGHBOR_TABLE_SIZE: 26
  EMBER_SOURCE_ROUTE_TABLE_SIZE: 254

  SL_DEVICE_INIT_HFXO_CTUNE: 140

  # required until https://github.com/NabuCasa/silabs-firmware-builder/pull/67 is merged
  # SL_DEVICE_INIT_HFXO_FREQ: 39000000
  # SL_DEVICE_INIT_HFXO_PRECISION: 500
