name: TubesZB MGM12 2021 Zigbee
device: MGM12P32F1024GE
base_project: src/zigbee_ncp
sdk: "gecko_sdk:4.4.4"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: ncp-uart-hw
  dynamic: ["ezsp_version"]
  baudrate: 115200

configuration:
  SL_RAIL_UTIL_PTI_MODE: RAIL_PTI_MODE_DISABLED
  SL_IOSTREAM_USART_VCOM_BAUDRATE: 115200
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: usartHwFlowControlNone

c_defines:
  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_USART_VCOM_TX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_TX_PIN:  0
  SL_IOSTREAM_USART_VCOM_TX_LOC:  0

  SL_IOSTREAM_USART_VCOM_RX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_RX_PIN:  1
  SL_IOSTREAM_USART_VCOM_RX_LOC:  0

  SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE: 64
  
  EMBER_PACKET_BUFFER_COUNT: 255
  EMBER_APS_UNICAST_MESSAGE_COUNT: 32
  EMBER_BROADCAST_TABLE_SIZE: 64
  EMBER_NEIGHBOR_TABLE_SIZE: 26
  EMBER_SOURCE_ROUTE_TABLE_SIZE: 254
  EMBER_MAX_END_DEVICE_CHILDREN: 32

