name: TubesZB MGM24 RCP
device: MGM240PA32VNN
base_project: src/ot-rcp
filename: "{manifest_name}_{ot_rcp_version.split('/')[-1]}_gsdk_{sdk_version}"

gbl:
  fw_type: ot-rcp
  dynamic: ["ot_rcp_version"]
  baudrate: 115200

add_components:
- id: simple_led
  instance: [board_activity]

configuration:
  SL_UARTDRV_USART_VCOM_BAUDRATE: 115200
  SL_RAIL_UTIL_PTI_MODE: RAIL_PTI_MODE_DISABLED
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: usartHwFlowControlCtsAndRts

c_defines:
  SL_UARTDRV_USART_VCOM_PERIPHERAL: USART0
  SL_UARTDRV_USART_VCOM_PERIPHERAL_NO: 0

  SL_UARTDRV_USART_VCOM_TX_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_TX_PIN:  6

  SL_UARTDRV_USART_VCOM_RX_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_RX_PIN:  5 

  SL_UARTDRV_USART_VCOM_CTS_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_CTS_PIN:  7

  SL_UARTDRV_USART_VCOM_RTS_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_RTS_PIN:  8

  # SL_SIMPLE_LED_BOARD_ACTIVITY_POLARITY: SL_SIMPLE_LED_POLARITY_ACTIVE_LOW
  # SL_SIMPLE_LED_BOARD_ACTIVITY_PORT:     gpioPortA
  # SL_SIMPLE_LED_BOARD_ACTIVITY_PIN:      1