name: SONOFF DONGLE-E Zigbee Router
device: EFR32MG21A020F768IM32
base_project: src/zigbee_router
filename: "{manifest_name}_{ezsp_version}_{baudrate}_{fw_variant}"
sdk: "simplicity_sdk:2024.12.0"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: zigbee_router
  ezsp_version: dynamic
  baudrate: 115200
  fw_variant: sw_flow

add_components:
  # Status
  - id: simple_led
    instance:
      - led0
  # BOOT
  - id: simple_button
    instance:
      - btn1

slcp_defines:
  SL_ZIGBEE_ADDRESS_TABLE_SIZE: 32
  SL_ZIGBEE_MULTICAST_TABLE_SIZE: 26
  SL_ZIGBEE_ROUTE_TABLE_SIZE: 16
  SL_ZIGBEE_DISCOVERY_TABLE_SIZE: 16

c_defines:
  SL_IOSTREAM_USART_VCOM_BAUDRATE: 115200
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: uartFlowControlSoftware

  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_USART_VCOM_TX_PORT: gpioPortB
  SL_IOSTREAM_USART_VCOM_TX_PIN:  1

  SL_IOSTREAM_USART_VCOM_RX_PORT: gpioPortB
  SL_IOSTREAM_USART_VCOM_RX_PIN:  0

  SL_IOSTREAM_USART_VCOM_CTS_PORT: 0
  SL_IOSTREAM_USART_VCOM_CTS_PIN:  0

  SL_IOSTREAM_USART_VCOM_RTS_PORT: 0
  SL_IOSTREAM_USART_VCOM_RTS_PIN:  0

  SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE: 64

  SL_SIMPLE_LED_LED0_POLARITY: SL_SIMPLE_LED_POLARITY_ACTIVE_LOW
  SL_SIMPLE_LED_LED0_PORT: gpioPortC
  SL_SIMPLE_LED_LED0_PIN: 0

  SL_SIMPLE_BUTTON_BTN1_MODE: SL_SIMPLE_BUTTON_MODE_INTERRUPT
  SL_SIMPLE_BUTTON_BTN1_PORT: gpioPortA
  SL_SIMPLE_BUTTON_BTN1_PIN: 0

  SL_CLOCK_MANAGER_HFXO_EN: 1
  SL_CLOCK_MANAGER_HFXO_CTUNE: 128
  SL_CLOCK_MANAGER_DEFAULT_HF_CLOCK_SOURCE: SL_CLOCK_MANAGER_DEFAULT_HF_CLOCK_SOURCE_HFXO

  SL_ZIGBEE_APS_UNICAST_MESSAGE_COUNT: 64
  SL_ZIGBEE_BROADCAST_TABLE_SIZE: 30
  SL_ZIGBEE_NEIGHBOR_TABLE_SIZE: 26
  SL_ZIGBEE_SOURCE_ROUTE_TABLE_SIZE: 200
  SL_ZIGBEE_MAX_END_DEVICE_CHILDREN: 32

  SL_RAIL_UTIL_RSSI_OFFSET: -11

  # all zigbee channels
  SL_ZIGBEE_AF_PLUGIN_NETWORK_STEERING_CHANNEL_MASK: 0x07fff800
  SL_ZIGBEE_AF_PLUGIN_NETWORK_STEERING_RADIO_TX_POWER: 20

  SL_ZIGBEE_AF_PLUGIN_CONCENTRATOR_CONCENTRATOR_TYPE: HIGH_RAM_CONCENTRATOR
  # <1-60>
  SL_ZIGBEE_AF_PLUGIN_CONCENTRATOR_MIN_TIME_BETWEEN_BROADCASTS_SECONDS: 30
  # <30-300>
  SL_ZIGBEE_AF_PLUGIN_CONCENTRATOR_MAX_TIME_BETWEEN_BROADCASTS_SECONDS: 180
  # <1-100>
  SL_ZIGBEE_AF_PLUGIN_CONCENTRATOR_ROUTE_ERROR_THRESHOLD: 3
  # <1-100>
  SL_ZIGBEE_AF_PLUGIN_CONCENTRATOR_DELIVERY_FAILURE_THRESHOLD: 1
